---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: tradition-cluster
  region: eu-central-1
  version: "1.23"

iam:
  withOIDC: true

vpc:
  id: "vpc-0c3d73c073dc1a45e"
  subnets:
    public:
      eu-central-1a:
        name: "public-subnet-1"
      eu-central-1b:
        name: "public-subnet-2"
      eu-central-1c:
        name: "public-subnet-3"

nodeGroups:
  - name: tradition-bottlerocket
    instanceType: t2.large
    desiredCapacity: 2
    amiFamily: Bottlerocket
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
    ssh:
      allow: true
      publicKeyName: linux_public_key
